### ISSUE TITLE
startup probe timeout is hardcoded and the node restarts before finishes startup sequence

### ISSUE THREAD

**Issue by pasztorl** [opensearch-project/opensearch-k8s-operator#418]
Hi,

I've created a cluster with the operator. The cluster up and running, everything worked well.
When I added some plugins to the cluster CRD (prometheus-exporter + s3 repository) the node needs more time to startup. With the default settings it is not enough to start before startup probe fails.
As a workaround if I stop the operator, modify the start up probe on the statefulset the cluster starts up successfully.

Questions:
The node with almost empty storage boots up around 5 minutes. There is no significant io or cpu usage. It is real that it needs minutes to start up?
There is a way to specify startup probe with the cluster CRD? (as I see the code currently not)

I've attached the startup log.
[graylog-opensearch-masters-1.log](https://github.com/Opster/opensearch-k8s-operator/files/10529990/graylog-opensearch-masters-1.log)

**Comment by swoehrl-mw** [comment]
Hi @pasztorl.

> The node with almost empty storage boots up around 5 minutes. There is no significant io or cpu usage. It is real that it needs minutes to start up?

In my experience an opensearch pod takes about 2-3 minutes to start. So 5 minutes sounds like something is wrong. From your description it is likely that the plugin installation takes too long (unfortunately the relevant log lines do not have timestamps, so it's impossible to tell).

> There is a way to specify startup probe with the cluster CRD? (as I see the code currently not)

This is currently not possible. I'm not sure if we should make it configurable or just increase the default timeout, maybe both. I'll mark this as a feature request.

**Comment by pasztorl** [comment]
Hi @swoehrl-mw,
Thanks for the feedback. How do you see when it can be implemented?

**Comment by swoehrl-mw** [comment]
@pasztorl 

> How do you see when it can be implemented?

Can't tell. That entirely depends on someone finding the time and energy to implement this. On that note: PRs from new contributors are always welcome.

> Can you suggest a workaround while it is not implemented?

Unfortunately not really. Other than finding out why the startup takes so long and speeding it up. 
You could also try to use a policy agent (gatekeeper, kyverno, ...) to patch the pods with a longer timeout.

**Comment by kwinkel** [comment]
Having the same issue in our development environment during maintenance work and the related slower times for provide the storage. We also include another plugins which takes some extra time. Restarts during this time are completely pain because the probe terminates the pod some time before the cluster would report status green.
For a quick improvement, it would help to increase the hardcoded values of `FailureThreshold`. To be able to override them is kind of the best solution for us users.

**Comment by vipinjn24** [comment]
I will be working on this change and will soon send in the pull request.
