### ISSUE TITLE
UpgradeChecker

### ISSUE THREAD

**Issue by idanl21** [opensearch-project/opensearch-k8s-operator#532]
**How does the Upgrade Checker work?**
The Upgrade Checker is an integrated component of the OpenSearch k8s Operator. Once a day, the Operator communicates with our server to verify if it's running the latest version. If an update is needed, a log message will be printed to notify you.

**What information is collected?**
The Upgrade Checker will collect and send general information regarding your cluster version. The Checker sends a unique identifier (UID) that is randomly created with the number of OpenSearch clusters connected and their version.
This data is necessary in order to determine which updates are needed based on current versions.

**Data transmission details**
The Upgrade Checker generates and sends a JSON file containing the following information to our server:
```
{
	"properties": {
		"clusterCount": 3,
		"operatorVersion": "2.2.1",
		"osClustersVersions": [
			"2.4.0",
			"2.5.0",
			"2.5.0"
		],
		"uid": "8HcTRnKaGe"
	}
}
```
Each field represents:
clusterCount: The number of OpenSearch clusters managed by the Operator.
operatorVersion: The Operator version
osClustersVersions: The versions of the managed OpenSearch clusters.
uid: A unique identifier (UID) generated upon each new installation or when upgrading to a version of the Operator that includes the Upgrade Checker.

**Usage of data and privacy**
We designed the Upgrade Checker with strict adherence to privacy principles. The information transmitted does not include any personal or sensitive data, only details about the OpenSearch Operator version and cluster versions it manages.

**Supporting this initiative**
By allowing the Upgrade Checker to operate, we’ll be able to provide the necessary updates to used versions and introduce new features resulting in a better experience. 

**Disabling the Upgrade Checker**
While we believe in the value of this initiative, we respect your choice if you do not wish to participate. The Upgrade Checker is enabled by default but can be turned off at any time. To disable it, adjust the 'UpgradeChecker' value to 'false' in your helm chart. If you need further assistance, please refer to our comprehensive documentation or contact our support team.
Thank you for your continued support and usage of the OpenSearch Kubernetes Operator. 

Related to [PR](https://github.com/Opster/opensearch-k8s-operator/pull/522)

**Comment by prudhvigodithi** [comment]
I see the PR is closed https://github.com/Opster/opensearch-k8s-operator/pull/522, so closing this issue as there is no plans to integrate the Upgrade Checker to the OpenSearch Operator.
@bbarani @swoehrl-mw @salyh
