### ISSUE TITLE
Cannot import project as module

### ISSUE THREAD

**Issue by saketmht** [opensearch-project/opensearch-k8s-operator#560]
I am trying to import the project as a module to use the opster APIs but I have been unsuccessful so far.

```
$ go get -v github.com/Opster/opensearch-k8s-operator
```
After this, tried to import it but got error 
```
go: finding module for package github.com/Opster/opensearch-k8s-operator
github.com/my-project/opensearchoperator imports
	github.com/Opster/opensearch-k8s-operator: module github.com/Opster/opensearch-k8s-operator@latest found (v2.3.1+incompatible), but does not contain package github.com/Opster/opensearch-k8s-operator
```
Probably because the go.mod file is not the top level directory but inside `opensearch-operator` dir.

Also tried
```
$ go get -v github.com/Opster/opensearch-k8s-operator/opensearch-operator
go: github.com/Opster/opensearch-k8s-operator/opensearch-operator@v0.0.0-20230705102953-d4c334f09f63: parsing go.mod:
        module declares its path as: opensearch.opster.io
                but was required as: github.com/Opster/opensearch-k8s-operator/opensearch-operator
```

What is the correct way to import opster as a module?

**Comment by swoehrl-mw** [comment]
Hi @saketmht. As the operator is a binary and not a library, importing it as a module is not supported.
What are you trying to accomplish?

**Comment by saketmht** [comment]
Hi @swoehrl-mw I am trying to use the opster APIs in my Go code, like how we import the k8s API, prometheus operator or other projects APIs. Something like

```
import (
   corev1 "k8s.io/api/core/v1"
   promoperapi "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
)

// And use the APIs
secret := corev1.Secret{}
smList := &promoperapi.ServiceMonitorList{}

// Similary import the opster APIs??
import (
   opsterv1 "github.com/Opster/opensearch-k8s-operator/opensearch-operator/api/v1"
)

// Use opster API?
opensearch := opsterv1.OpenSearchCluster{}
```

**Comment by saketmht** [comment]
I think there might 2 factors for why this is not working:
1. the go.mod not being the top level directory
2. the go.mod having module name as `opensearch.opster.io`

For most projects I see that the module name is the same as the path the `go.mod` file is in like `github.com/../..`  . For example, the prom operator go.mod
https://github.com/prometheus-operator/prometheus-operator/blob/main/go.mod

**Comment by swoehrl-mw** [comment]
@saketmht I'm no expert on how go modules work, but if you find out how to do it and the changes can be done without producing incompatible user-visible changes, then I think this is something that we can support.

**Comment by saketmht** [comment]
@swoehrl-mw Even I don't have much experices with go modules but from what I understand from [this](https://go.dev/ref/mod#vcs-dir) (I will copy paste it below)

> Once a module’s repository has been checked out at a specific revision, the go command must locate the directory that contains the module’s go.mod file (the module’s root directory).

> Recall that a [module path](https://go.dev/ref/mod#module-path) consists of three parts: a repository root path (corresponding to the repository root directory), a module subdirectory, and a major version suffix (only for modules released at v2 or higher).

> For most modules, the module path is equal to the repository root path, so the module’s root directory is the repository’s root directory.

> Modules are sometimes defined in repository subdirectories. This is typically done for large repositories with multiple components that need to be released and versioned independently. Such a module is expected to be found in a subdirectory that matches the part of the module’s path after the repository root path. For example, suppose the module example.com/monorepo/foo/bar is in the repository with root path example.com/monorepo. Its go.mod file must be in the foo/bar subdirectory.

> If a module is released at major version v2 or higher, its path must have a [major version suffix](https://go.dev/ref/mod#major-version-suffixes). A module with a major version suffix may be defined in one of two subdirectories: one with the suffix, and one without. For example, suppose a new version of the module above is released with the path example.com/monorepo/foo/bar/v2. Its go.mod file may be in either foo/bar or foo/bar/v2.


So I think the `go.mod` should have module name as `opensearch-operator` instead of `opensearch.opster.io` And based on this 

> If a module is defined in a subdirectory within the repository, that is, the [module subdirectory](https://go.dev/ref/mod#glos-module-subdirectory) portion of the module path is not empty, then each tag name must be prefixed with the module subdirectory, followed by a slash. For example, the module golang.org/x/tools/gopls is defined in the gopls subdirectory of the repository with root path golang.org/x/tools. The version v0.4.0 of that module must have the tag named gopls/v0.4.0 in that repository.

There should be an additional tag `opensearch-operator/v2.x` for releases
Maybe @idanl21 has an idea about this?

**Comment by swoehrl-mw** [comment]
> So I think the `go.mod` should have module name as `opensearch-operator` instead of `opensearch.opster.io` And based on this

Will mean a one-time refactoring to change all the imports, but doable.

> There should be an additional tag `opensearch-operator/v2.x` for releases

That should not be a problem. Our normal release pipeline already sets the `vx.y` tag, so setting another one is easy.

**Comment by cthtrifork** [comment]
Any news on this? 👍

**Comment by swoehrl-mw** [comment]
@saketmht With PR #645 merged, is there anything else that needs to be done to resolve this issue?

**Comment by saketmht** [comment]
@swoehrl-mw I think we are good to close this.
