### ISSUE TITLE
Allow to configure CPU and memory limits on opensearch-securityconfig-update job

### ISSUE THREAD

**Issue by jbnjohnathan** [opensearch-project/opensearch-k8s-operator#613]
Due to namespaces quotas in our cluster all containers needs to have cpu and memory limits.
I have set it for everything I can find in the CR, but the `opensearch-securityconfig-update` cannot create a pod with error:

```
Warning  FailedCreate  3m43s (x263 over 16h)  job-controller  (combined from similar events): Error creating: pods "opensearch-securityconfig-update-f95jj" is forbidden: failed quota: mynamespace-quota: must specify limits.cpu for: updater; limits.memory for: updater
```

I think this is the code that is creating the job: https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/builders/cluster.go#L954
I don't see that `resource` is used as a parameter to the creation of pod definition for the job.

**Comment by ramonheras** [comment]
@swoehrl-mw could [this](https://github.com/ramonheras/opensearch-k8s-operator/tree/feature/propagate-init-resources-config-to-all-init-containers-and-jobs) be posible solution? Just asking before submitting the PR

**Comment by swoehrl-mw** [comment]
@ramonheras Partially.
For the init containers, yes, here the resources from `spec.initHelper.resources` can and should be used.
The snaptshotrepo update job, as it is a temporary workaround anyway, can use the same.
But for the securityconfig update job I think there should be separate resources (I would say `spec.security.config.updateJob.resources`).
