### ISSUE TITLE
Add pprof capabilities to the operator

### ISSUE THREAD

**Issue by swoehrl-mw** [opensearch-project/opensearch-k8s-operator#626]
There have been several instances where users have reported OOM kills of the operator pod without any obvious causes (#585, #612). Diagnosing such failures and determining a cause just from logs is basically impossible. I propose we add a [pprof](https://pkg.go.dev/runtime/pprof) endpoint to the operator (exposed only on localhost for security, maybe even disabled by default and add a toggle to the helm values) and add documentation how users can pull a memory dump.

**Comment by mrvdcsg** [comment]
I linked this as memory leaks are observed in both 2.5.1 and 2.6.0 versions of the operator. This could help determine root cause so the leaks can be resolved.
