### ISSUE TITLE
Add resource limitation to bootstrap pod

### ISSUE THREAD

**Issue by idanl21** [opensearch-project/opensearch-k8s-operator#667]
The bootstrap node has key roles when forming a cluster.
On the current implementation of k8 operator the bootstrap node does not have resource limitations and on some of our customers it looks like this cause a problem as part of the mandatory limitation they have on their envs.

So we need do 2 things:
1.  Add resource limitation to bootstrap node.
2. Add documentation on the subject.

**Comment by siegenthalerroger** [comment]
Number 1 is already possible however it is undocumented. There is a top-level `bootstrap` field in the CRD that allows setting the `resources` (verified as working for me).
