### ISSUE TITLE
[BUG] helm repo not found

### ISSUE THREAD

**Issue by fabiocorneti** [opensearch-project/opensearch-k8s-operator#672]
### What is the bug?

Run:

```
helm repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator/
```

The operation fails as https://opster.github.io/opensearch-k8s-operator/ returns a 404 since the 1st of December or so.

### How can one reproduce the bug?

```
helm repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator/
```

### What is the expected behavior?

The chart repo should be added.

### What is your host/environment?

MacOS Sonoma

### Do you have any screenshots?

n/a

### Do you have any additional context?

I understand the operator is not in this repository but it is referenced by the official documentation.

**Comment by mausch** [comment]
I was just about to file this, you beat me to it :slightly_smiling_face: 

> I understand the operator is not in this repository

Oh? where is it? i.e. is there a workaround?

**Comment by nward** [comment]
Is this because this has moved from the Opster GitHub org to opensearch-project?

**Comment by nward** [comment]
@wbeckler the opster repo redirects to this, and the issues etc. are all here - I think it’s been moved rather than forked.

**Comment by wbeckler** [comment]
I just opened an issue in the Eliatra fork mentioning this so that they can hopefully remove the duplicate.

**Comment by mausch** [comment]
ok so replace https://opster.github.io/opensearch-k8s-operator/ with https://opensearch-project.github.io/opensearch-k8s-operator/ I think.

**Comment by nward** [comment]
@mausch yes this has worked for me just fine - thanks

**Comment by julienkosinski** [comment]
@nward Well...
`helm repo add opensearch-operator https://opensearch-project.github.io/opensearch-k8s-operator/`

It still gives me:
```
helm install opensearch-operator opensearch-operator/opensearch-operator
Error: INSTALLATION FAILED: failed to fetch https://Opster.github.io/opensearch-k8s-operator/opensearch-operator-2.4.0.tgz : 404 Not Found
```

I tried to delete caching stuff, but the problem remains, is there some broken redirect somewhere?

**Comment by julienkosinski** [comment]
> @julienkosinski do you have an existing helm repo with that name? You may need to delete it before adding a new one?

Well I did but I deleted it...

**Comment by Rockawear** [comment]
For some reason, the new repo `https://opensearch-project.github.io/opensearch-k8s-operator/` is still directing me to `https://Opster.github.io/opensearch-k8s-operator` this is kustomize which try to pull it on the fly. seeing below error
``` 
Error: failed to fetch https://Opster.github.io/opensearch-k8s-operator/opensearch-operator-2.4.0.tgz : 404 Not Found
```

**Comment by nward** [comment]
It looks like the index file still points to Opster. I hadn't noticed this because I already had a copy of the helm chart installed - I was getting failures on FluxCD updating HelmRepository instances.

https://opensearch-project.github.io/opensearch-k8s-operator/index.yaml to see the URLs.

**Comment by mausch** [comment]
I ended up cloning this repo and then installed the helm chart from file.

**Comment by prudhvigodithi** [comment]
Hey Everyone just created an issue to track all the broken operator functionaries https://github.com/opensearch-project/opensearch-k8s-operator/issues/674#issue-2025017085, please add your thoughts to the issue created. Thank you
