### ISSUE TITLE
[BUG] Operator Functionality broke after repo transferred from Opster to OpenSearch org.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-k8s-operator#674]
### What is the bug?
The repo was recently transferred from Opster Github org to OpenSearch org, this broke the operator from being complied and installed. Fix the following issues which should continue the customers to use (and install) the operator.

- [x] Fix the broken helm URL's https://github.com/opensearch-project/opensearch-k8s-operator/issues/672.

- [x] Migrate the artifcathub Helm repo to [opensearch-org](https://artifacthub.io/packages/search?org=opensearch-project&sort=relevance&page=1).
- [x] Update the code docker image to change from https://gallery.ecr.aws/opsterio/opensearch-operator to official OpenSearch [Docker](https://hub.docker.com/u/opensearchproject) and [ECR registry](https://gallery.ecr.aws/opensearchproject). https://github.com/opensearch-project/opensearch-k8s-operator/pull/712
- [x] Update the README installation instructions and helm artifacthub with right URL's to use. https://github.com/opensearch-project/opensearch-k8s-operator/pull/710
- [x] Update the Opster reference to OpenSearch guidelines.
- [x] Refactor the code and change the packages to opensearch.org. https://github.com/opensearch-project/opensearch-k8s-operator/pull/698
- [x] On board the repo the OpenSearch release process https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process. https://github.com/opensearch-project/opensearch-k8s-operator/pull/710

Maintainers and other operator users to please advice more if missing any other additional steps.
@bbarani  @idanl21 @ido-opster @dbason @swoehrl-mw

**Comment by ammmze** [comment]
I've got a PR (#673) to minimally update the urls in the helm index file so that should enable people to be able to install via helm again.

**Comment by prudhvigodithi** [comment]
Transferred the helm repo in artifact-hub to opensearch-project organization
https://artifacthub.io/packages/search?org=opensearch-project&sort=relevance&page=1.
Thanks

**Comment by pasztorl** [comment]
Hi,

helm repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator/
Error: looks like "https://opster.github.io/opensearch-k8s-operator/" is not a valid chart repository or cannot be reached: failed to fetch https://opster.github.io/opensearch-k8s-operator/index.yaml : 404 Not Found


seems not working here.

**Comment by pasztorl** [comment]
Also the docs needs to update:
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/helm/

**Comment by pasztorl** [comment]
sorry, docs are ok, it was my mistake

**Comment by evheniyt** [comment]
Opster image registry is not available anymore

**Comment by prudhvigodithi** [comment]
Closing this Meta issue as the tasks listed are accomplished, please feel free to re-open if reuired.
Thanks
Adding @bbarani
