### ISSUE TITLE
[BUG] ArtifcatHub installation failed

### ISSUE THREAD

**Issue by idanl21** [opensearch-project/opensearch-k8s-operator#676]
Hey friends
got that issue from customer

```
$ helm repo list
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/opensearch-beta-china-kubeconfig.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/opensearch-beta-china-kubeconfig.yaml
NAME               	URL
opensearch-operator	https://opensearch-project.github.io/opensearch-k8s-operator/

$ helm install opensearch-operator opensearch-operator/opensearch-operator
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ubuntu/.kube/opensearch-beta-china-kubeconfig.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ubuntu/.kube/opensearch-beta-china-kubeconfig.yaml
Error: INSTALLATION FAILED: failed to fetch https://opster.github.io/opensearch-k8s-operator/opensearch-operator-2.4.0.tgz : 404 Not Found
```

I think that you should edit the Artifacthub link cause of the repo change to Opensearch Org.
We need to change the ownership of the ArtifactHub repo

**Comment by prudhvigodithi** [comment]
Thanks @idanl21, there is already an META issue opened related to this topic https://github.com/opensearch-project/opensearch-k8s-operator/issues/674, please check.

**Comment by pasztorl** [comment]
helm repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator/
Error: looks like "https://opster.github.io/opensearch-k8s-operator/" is not a valid chart repository or cannot be reached: failed to fetch https://opster.github.io/opensearch-k8s-operator/index.yaml : 404 Not Found

**Comment by pasztorl** [comment]
sorry, my mistake
