### ISSUE TITLE
The default `PeriodSeconds` and `InitialDelaySeconds` settings are insufficient for some low-performance hardware, causing the containers to repeatedly restart.

### ISSUE THREAD

**Issue by CoderYellow** [opensearch-project/opensearch-k8s-operator#691]
It seems that these [configurations](https://github.com/opensearch-project/opensearch-k8s-operator/blob/82bac392f879a1cf3f48c5263046659f9bff8cbc/opensearch-operator/pkg/builders/cluster.go#L196) are hardcoded. Could you provide a method to configure them?

**Comment by CoderYellow** [comment]
When I check the log, it shows that the process never gets the chance to start completely before being killed by the Kubernetes scheduler.

**Comment by kwinkel** [comment]
https://github.com/opensearch-project/opensearch-k8s-operator/issues/418

**Comment by vipinjn24** [comment]
Raised a pr for this and expecting operator team to release this change with next version, as of now you can use the changes in the branch to update crds and create a docker image for operator.

I guess image pull policy never will let you fetch local docker images. Or you can use a docker registry for this purpose.
