### ISSUE TITLE
[BUG] Operator ClusterRole manifest inconsistent with Helm ClusterRole

### ISSUE THREAD

**Issue by onesolpark** [opensearch-project/opensearch-k8s-operator#717]
### What is the bug?
Operator ClusterRoles created through kubebuilder is inconsistent with ClusterRole in Helm Chart. 

### How can one reproduce the bug?
Deploy opensearch operator through Makefile built with kubebuilder
```
make build manifests
IMG={image_url} make deploy
```

### What is the expected behavior?
ClusterRole manifests build thorugh kubebuilder should be consistent with Helm chart.

### What is your host/environment?
N/A

### Do you have any screenshots?
Error logs 

E0202 01:26:51.760259       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.ServiceMonitor: failed to list *v1.ServiceMonitor: servicemonitors.monitoring.coreos.com is forbidden: User "system:serviceaccount:opensearch-operator-system:opensearch-operator-controller-manager" cannot list resource "servicemonitors" in API group "monitoring.coreos.com" at the cluster scope

E0202 01:29:41.502256       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:opensearch-operator-system:opensearch-operator-controller-manager" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope

### Do you have any additional context?
Adding appropriate kubebuilder codegen marker will solve this.
```
//+kubebuilder:rbac:groups=core,resources=persistentvolumeclaims,verbs=delete;get;list;patch;update;watch
```

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks for your contribution @onesolpark, I will take a look at your PR.
Adding @bbarani @salyh @jochenkressin @pchmielnik @swoehrl-mw
