### ISSUE TITLE
[FEATURE] Request for an 2.5.2 release

### ISSUE THREAD

**Issue by cthtrifork** [opensearch-project/opensearch-k8s-operator#749]
There is some fixes in the main branch regarding custom resources which are quite desirable:
https://github.com/opensearch-project/opensearch-k8s-operator/compare/v2.5.0...main

Could we get a new release (perhaps a patch for 2.5.2) or is there a schedule for releases I can follow somewhere? I have not been able to find any in the documentation

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @cthtrifork, I agree we need a 2.5.2 release. Adding @bbarani @salyh @jochenkressin @pchmielnik @swoehrl-mw 
Thanks

**Comment by prudhvigodithi** [comment]
I have created an issue https://github.com/opensearch-project/opensearch-k8s-operator/issues/776 for v2.6.0 release.
Thanks
