### ISSUE TITLE
[FEATURE] Enhance CI workflows and update actions

### ISSUE THREAD

**Issue by salyh** [opensearch-project/opensearch-k8s-operator#773]
### Is your feature request related to a problem?
We have old workflow actions using node 16 which triggers deprecation warnings.
There also minor other issues with the CI like hard coded go version and usage of unmaintained actions.
Also a few checks are missing like inting of the helm charts

### What solution would you like?
- Updat checkout action to v4
- Updat setup-buildx-action action to v3
- setup-go action should use the go version specified in go.work (with caching disabled)
- update golangci-lint version to 1.57
- Add helm chart linting to the CI
- Add "make install" smoketest to the CI
- Updat helm version to 3.14 and update setup-helm action to v4
- Replace unmaintained actions/create-release
- Update envtest k8s version to 1.27
- Update kustomize to 5.3.0
- Update mockery to 2.42
- Fix go version in opensearch-operator/functionaltests/go.mod

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @salyh, I will go ahead and review the PR.
