### ISSUE TITLE
Can we disable basic authentication?

### ISSUE THREAD

**Issue by SakibAbrar** [opensearch-project/opensearch-k8s-operator#778]
I am trying to launch a cluster on an AWS EKA cluster with the basic auth disabled to make internal usage from the service more straightforward. Also can we modify the readiness probe command now? It assumes to have basic auth enabled by default. 

I want to achieve something similar to: `plugins.security.disabled: true` just like https://opensearch.org/docs/latest/security/configuration/disable/

**Comment by swoehrl-mw** [comment]
Hi @SakibAbrar. The operator does not support disabling the security plugin, it always requires auth and TLS.
You could try to configure [anonymous authentication](https://opensearch.org/docs/latest/security/access-control/anonymous-authentication/)

**Comment by SakibAbrar** [comment]
Thanks @swoehrl-mw 
Closing this issue
