### ISSUE TITLE
[BUG] OpensearchIndexTemplate does not use timestamp_field

### ISSUE THREAD

**Issue by mskitroot** [opensearch-project/opensearch-k8s-operator#798]
### What is the bug?
When creating an Index Template with a dataStream Object defining the timestamp_field as in the CRD this is then removed from the definition on the cluster reverting to the default `timestamp_field: @timestamp`

### How can one reproduce the bug?
Apply an OpensearchIndexTemplate with

```
dataStream:
  timestamp_field:
    name: myTimeField
```
The definition in the cluster should have the above instead it reverts to 
```
dataStream: {}
```
### What is the expected behavior?
The timestamp_field should be used and applied on the definition and in the Index Template

### What is your host/environment?
k3s on Ubuntu running operator version 2.6.0

**Comment by mskitroot** [comment]
@cgroschupp It may be an inconsistency between CRD and definition in opensearch_index_types.go?

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @mskitroot, there is an open PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/810 to fix this. Thanks to @swoehrl-mw

**Comment by swoehrl-mw** [comment]
Hi @mskitroot. I've validated that the PR fixes your bug. It will be part of the next release (no timeline yet). So I'm closing this issue.
