### ISSUE TITLE
[BUG] Operator 2.6.0 can't be uninstalled cleanly due to finalizer

### ISSUE THREAD

**Issue by 2mf** [opensearch-project/opensearch-k8s-operator#814]
### What is the bug?
OpenSearch can not be uninstalled via `helm uninstall` and deletion of namespace afterwards due to finializer is blocking the deletion of a `OpensearchRole` resource.
2.5.1 works perfectly fine.

### How can one reproduce the bug?
Helm install operator 2.6.1 and add a OpensearchRole.  Helm uninstall operator.

### What is the expected behavior?
Clean uninstall without any manual cleanup afterwards.

### What is your host/environment?
 K8s 1.28.7

### Do you have any screenshots?
N/A

### Do you have any additional context?
N/A

**Comment by swoehrl-mw** [comment]
Hi @2mf. This IMO is not something the operator should or can easily support. Uninstalling the operator without uninstalling clusters first will lead to timing issues with the operator pod already stopping before it can uninstall the clusters. It is your responsibility to keep an uninstall order.
