### ISSUE TITLE
What is the diff between master role vs data role vs cluster_manager role?

### ISSUE THREAD

**Issue by rameshar16** [opensearch-project/opensearch-k8s-operator#827]
Hi Team,

Please help on the below request.

What is the diff between master role vs data role vs cluster_manager role?

Thank you,
Ramesh

**Comment by lukas-vlcek** [comment]
Hi,

I think you can find the following article useful:
https://opster.com/guides/opensearch/opensearch-data-architecture/how-to-configure-opensearch-node-roles/

**Comment by rameshar16** [comment]
Thank you @lukas-vlcek  for sharing the useful info.

**Comment by lukas-vlcek** [comment]
On top of that I think you can find relevant information in the OpenSearch documentation too:
- https://opensearch.org/docs/latest/tuning-your-cluster/#nodes
