### ISSUE TITLE
The OpenSearch Dashboards return a 502 error when accessed via the Ingress route.

### ISSUE THREAD

**Issue by anjanaprasd** [opensearch-project/opensearch-k8s-operator#887]
### What is the bug?
The OpenSearch Dashboards return a 502 error when accessed via the Ingress route.

### How can one reproduce the bug?
The OpenSearch Dashboards return a 502 error when accessed via the Ingress route.

### What is the expected behavior?
I'm new to OpenSearch, and I used the OpenSearch Operator to deploy an OpenSearch cluster in Kubernetes. I created a Traefik ingress route to access the OpenSearch dashboard, but when I try to access the dashboard via the ingress resource, I receive a 502 error. I checked the logs, and I see the same message being printed, but there are no errors or restarts in the dashboard pods. 

Additionally, I deployed the cluster with the default configuration and didn’t change anything.

Could you please assist me with this?

### What is your host/environment?
Alma Linux
Kubernetes

### Do you have any screenshots?
Only getting 502 error accessing the dashboard.

**Comment by anjanaprasd** [comment]
close

**Comment by anjanaprasd** [comment]
close

**Comment by arshashi** [comment]
If you enable tls: true, you need to provide additional annotations to pass through https in the ingress. Please refer the ingress annotations for reference

`  dashboards:
    additionalVolumes:
    - name: cachain
      path: /usr/share/opensearch/config/cachain
      secret:
        secretName: cachain
    opensearchCredentialsSecret:
      name: dashboards-credentials  # This is the name of your secret that contains the credentials for Dashboards to use
    annotations:
      traffic.sidecar.istio.io/includeInboundPorts: "*"
      traffic.sidecar.istio.io/excludeOutboundPorts: "9200,9300"
      traffic.sidecar.istio.io/excludeInboundPorts: "9200,9300"
    tls:
      enable: true
      generate: true
    version: 2.14.0`

Ingress

`apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/secure-backends: "true"
    name: opensearch-es-ing
    namespace: demo
  spec:
    ingressClassName: nginx
    rules:`

**Comment by anjanaprasd** [comment]
@arshashi  Thank you very much for your response.
